# India Flood Dataset — Initial Discovery

This notebook performs the initial audit of the raw India flood dataset.

Important:
- The raw dataset is read-only.
- No modifications are made to the raw CSV.
- Existing cleaned/feature-engineered datasets are not used at this stage.
- No assumptions are made about the target or feature definitions.

In [1]:
from pathlib import Path
import pandas as pd

# Project root
PROJECT_ROOT = Path.cwd().parent

# Raw India dataset
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw" / "India_Flood_Inventory_v3 (2).csv"

print("Project root:", PROJECT_ROOT)
print("Raw dataset path:", RAW_DATA_PATH)
print("File exists:", RAW_DATA_PATH.exists())

if not RAW_DATA_PATH.exists():
    raise FileNotFoundError(
        f"Raw India dataset not found at:\n{RAW_DATA_PATH}"
    )

# Load raw dataset
df_raw = pd.read_csv(RAW_DATA_PATH)

print("\nRaw India dataset loaded successfully.")
print("Shape:", df_raw.shape)

print("\nColumn names:")
for i, column in enumerate(df_raw.columns, start=1):
    print(f"{i:>3}. {column}")

print("\nData types:")
print(df_raw.dtypes)

print("\nFirst 5 rows:")
display(df_raw.head())

Project root: c:\Users\KIIT\Desktop\AI-Disaster-Intelligence-System
Raw dataset path: c:\Users\KIIT\Desktop\AI-Disaster-Intelligence-System\data\raw\India_Flood_Inventory_v3 (2).csv
File exists: True

Raw India dataset loaded successfully.
Shape: (6876, 23)

Column names:
  1. Unnamed: 0
  2. UEI
  3. Start Date
  4. End Date
  5. Duration(Days)
  6. Main Cause
  7. Location
  8. Districts
  9. State
 10. Latitude
 11. Longitude
 12. Severity
 13. Area Affected
 14. Human fatality
 15. Human injured
 16. Human Displaced
 17. Animal Fatality
 18. Description of Casualties/injured
 19. Extent of damage
 20. Event Source
 21. Event Souce ID
 22. District_LGD_Codes
 23. State_Codes

Data types:
Unnamed: 0                             int64
UEI                                      str
Start Date                               str
End Date                                 str
Duration(Days)                       float64
Main Cause                               str
Location                             float64
Districts                                str
State                                    str
Latitude                             float64
Longitude                            float64
Severity                             float64
Area Affected                        float64
Human fatality                       float64
Human injured                        float64
Human Displaced                          str
Animal Fatality                          str
Description of Casualties/injured        str
Extent of damage                         str
Event Source                             str
Event Souce ID                       float64
District_LGD_Codes                       str
State_Codes                              str
dtype: object

First 5 rows:

,Unnamed: 0,UEI,Start Date,End Date,Duration(Days),Main Cause,Location,Districts,State,Latitude,...,Human fatality,Human injured,Human Displaced,Animal Fatality,Description of Casualties/injured,Extent of damage,Event Source,Event Souce ID,District_LGD_Codes,State_Codes
0,563,UEI-IMD-FL-1967-0001,02-07-1967 00:00,08-07-1967 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,18
1,564,UEI-IMD-FL-1967-0002,22-07-1967 00:00,28-07-1967 00:00,7.0,flood,NaN,NaN,"Maharashtra, Gujarat",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,"27,24"
2,565,UEI-IMD-FL-1967-0003,01-08-1967 00:00,30-08-1967 00:00,30.0,flood,NaN,NaN,Uttar Pradesh,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,IMD,NaN,NaN,9
3,566,UEI-IMD-FL-1967-0004,08-09-1967 00:00,09-09-1967 00:00,2.0,flood,NaN,"Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapa...","Odisha, Bihar, Uttar Pradesh, Madhya Pradesh, ...",NaN,...,NaN,NaN,NaN,NaN,NaN,Marooning of Barwer Express,IMD,NaN,"348, 352, 356, None, 368, 345, 349, 350, 359, ...","21,10,9,23,8,6"
4,567,UEI-IMD-FL-1968-0001,22-06-1968 00:00,28-06-1968 00:00,7.0,flood,NaN,NaN,Assam,NaN,...,NaN,NaN,NaN,NaN,NaN,"Affecting about one million people,an area of ...",IMD,NaN,NaN,18

In [2]:
# Complete schema and data-quality overview

schema_df = pd.DataFrame({
    "Column": df_raw.columns,
    "Data Type": df_raw.dtypes.astype(str).values,
    "Non-Null Count": df_raw.notna().sum().values,
    "Missing Count": df_raw.isna().sum().values,
    "Missing %": (df_raw.isna().mean() * 100).round(2).values,
    "Unique Values": df_raw.nunique(dropna=True).values
})

print("RAW INDIA DATASET — COMPLETE SCHEMA")
print("=" * 80)

display(schema_df)

print("\nDataset shape:", df_raw.shape)

print("\nTotal missing values:", df_raw.isna().sum().sum())
print(
    "Overall missing percentage:",
    round(df_raw.isna().mean().mean() * 100, 2),
    "%"
)

print("\nDuplicate rows:", df_raw.duplicated().sum())

RAW INDIA DATASET — COMPLETE SCHEMA
================================================================================

,Column,Data Type,Non-Null Count,Missing Count,Missing %,Unique Values
0,Unnamed: 0,int64,6876,0,0.00,6876
1,UEI,str,6876,0,0.00,6876
2,Start Date,str,6856,20,0.29,3684
3,End Date,str,6856,20,0.29,3692
4,Duration(Days),float64,6857,19,0.28,61
5,Main Cause,str,6845,31,0.45,579
6,Location,float64,0,6876,100.00,0
7,Districts,str,6817,59,0.86,2892
8,State,str,6876,0,0.00,82
9,Latitude,float64,0,6876,100.00,0
10,Longitude,float64,0,6876,100.00,0
11,Severity,float64,0,6876,100.00,0
12,Area Affected,float64,0,6876,100.00,0
13,Human fatality,float64,3770,3106,45.17,183
14,Human injured,float64,1058,5818,84.61,62
15,Human Displaced,str,122,6754,98.23,23
16,Animal Fatality,str,571,6305,91.70,247
17,Description of Casualties/injured,str,3267,3609,52.49,2487
18,Extent of damage,str,3755,3121,45.39,3612
19,Event Source,str,6876,0,0.00,1
20,Event Souce ID,float64,0,6876,100.00,0
21,District_LGD_Codes,str,6572,304,4.42,2482
22,State_Codes,str,6618,258,3.75,65

Dataset shape: (6876, 23)

Total missing values: 70680
Overall missing percentage: 44.69 %

Duplicate rows: 0

In [3]:
# Display each column with a few representative non-null values

print("REPRESENTATIVE VALUES BY COLUMN")
print("=" * 80)

for column in df_raw.columns:
    print(f"\n[{column}]")
    print("dtype:", df_raw[column].dtype)
    print("sample values:")
    print(df_raw[column].dropna().head(5).tolist())

REPRESENTATIVE VALUES BY COLUMN
================================================================================

[Unnamed: 0]
dtype: int64
sample values:
[563, 564, 565, 566, 567]

[UEI]
dtype: str
sample values:
['UEI-IMD-FL-1967-0001', 'UEI-IMD-FL-1967-0002', 'UEI-IMD-FL-1967-0003', 'UEI-IMD-FL-1967-0004', 'UEI-IMD-FL-1968-0001']

[Start Date]
dtype: str
sample values:
['02-07-1967 00:00', '22-07-1967 00:00', '01-08-1967 00:00', '08-09-1967 00:00', '22-06-1968 00:00']

[End Date]
dtype: str
sample values:
['08-07-1967 00:00', '28-07-1967 00:00', '30-08-1967 00:00', '09-09-1967 00:00', '28-06-1968 00:00']

[Duration(Days)]
dtype: float64
sample values:
[7.0, 7.0, 30.0, 2.0, 7.0]

[Main Cause]
dtype: str
sample values:
['flood', 'flood', 'flood', 'flood', 'flood']

[Location]
dtype: float64
sample values:
[]

[Districts]
dtype: str
sample values:
['Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapada, Balangir, Boudh, Cuttack, Kandhamal, Nayagarh, Khordha, Kalahandi, Jagatsinghapur, Puri, Nagpur, Rayagada, Koraput, Malkangiri, Anugul, Kendrapara, Ganjam, Gajapati, Mayurbhanj, Sundargarh, Kendujhar, Baleshwar, Jharsuguda, Bargarh, Deogarh, Sambalpur, Pashchim Champaran, Purbi Champaran, Sitamarhi, Sheohar, Gopalganj, Samastipur, Katihar, Khagaria, Bhojpur, Buxar, Darbhanga, Saharsa, Kaimur (Bhabua), Rohtas, Jamui, Banka, Nawada, Gaya, Munger, Vaishali, Begusarai, Bhagalpur, Lakhisarai, Sheikhpura, Arwal, Jehanabad, Nalanda, Patna, Saran, Siwan, Muzaffarpur, Madhepura, Araria, Supaul, Madhubani, Purnia, Kishanganj, Aurangabad, Amroha, Hapur, Bareilly, Pilibhit, Bulandshahr, Gautam Buddha Nagar, Kheri, Budaun, Bahraich, Shahjahanpur, Aligarh, Kasganj, Mathura, SShrawasti, Sitapur, Hathras, Etah, Hardoi, Farrukhabad, Firozabad, Siddharthnagar, Mainpuri, Mahrajganj, Agra, Gonda, Bara Banki, Kushinagar, Kannauj, Lucknow, Basti, Gorakhpur, Sant Kabir Nagar, Unnao, Etawah, Kanpur nagar Nagar, Auraiya, Ayodhya, Kanpur nagar Dehat, Deoria, Sultanpur, Ambedkar Nagar, Rae Bareli, Jalaun, Azamgarh, Mau, Fatehpur, Ballia, Jaunpur, Jhansi, Banda, Ghazipurr, Kaushambi, Prayagraj, Varanasi, Chitrakoot, Chandauli, Bhadohi, Mirzapur, Lalitpur, Sonbhadra, Amethi, Ghaziabad, Sambhal, Mahoba, Saharanpur, Bijnor, Muzaffarnagar, Baghpat, Meerut, Moradabad, Rampur, Shamli, Balrampur, Hamirpur, Pratapgarh, Burhanpur, Morena, Bhind, Gwalior, Sheopur, Shivpuri, Tikamgarh, Neemuch, Rewa, Satna, Guna, Ashoknagar, Mandsaur, Singrauli, Sidhi, Sagar, Damoh, Shajapur, Vidisha, Rajgarh, Shahdol, Katni, Umaria, Ratlam, Bhopal, Ujjain, Raisen, Sehore, Jabalpur, Dewas, Anuppur, Jhabua, Dindori, Narsimhapur, Dhar, Indore, Mandla, Narmadapuram, Seoni, Alirajpur, Chhindwara, Harda, Khargone (Khargone (West Nimar)), East Nimar, Balaghat, Barwani, Agar-Malwa, Datia, Chhatarpur, Panna, Betul, Niwari, Churu, Jhunjhunu, Jaisalmer, Sikar, Alwar, Jaipur, Jodhpur, Bharatpur, Nagaur, Dausa, Karauli, Dholpur, Barmer, Sawai Madhopur, Tonk, Pali, Bhilwara, Jalore, Bundi, Kota, Sirohi, Baran, Udaipur, Jhalawar, Dungarpur, Banswara, Ajmer, Rajsamand, Chittorgarh, Ganganagar, Hanumangarh, Bikaner, Pratapgarh, Jhajjar, Gurugram, Faridabad, Mahendragarh, Rewari, Nuh, Palwal, Charki Dadri, Yamunanagar, Kurukshetra, Kaithal, Sirsa, Karnal, Jind, Fatehabad, Hisar, Panipat, Sonipat, Bhiwani, Rohtak, Panchkula, Ambala', 'Kasaragod, Wayanad, Kozhikode, Malappuram, Palakkad, Thrissur, Idukki, Ernakulam, Alappuzha, Kottayam, Pathanamthitta, Kollam, Thiruvananthapuram, Kannur, Churu, Jhunjhunun, Jaisalmer, Sikar, Alwar, Jaipur, Jodhpur, Bharatpur, Nagaur, Dausa, Karauli, Dholpur, Barmer, Sawai Madhopur, Tonk, Pali, Bhilwara, Jalore, Bundi, Kota, Sirohi, Baran, Udaipur, Jhalawar, Dungarpur, Banswara, Ajmer, Rajsamand, Chittorgarh, Ganganagar, Hanumangarh, Bikaner, Pratapgarh, Jhajjar, Gurugram, Faridabad, Mahendragarh, Rewari, Nuh, Palwal, Charki Dadri, Yamunanagar, Kurukshetra, Kaithal, Sirsa, Karnal, Jind, Fatehabad, Hisar, Panipat, Sonipat, Bhiwani, Rohtak, Panchkula, Ambala, Pashchim Champaran, Purbi Champaran, Sitamarhi, Sheohar, Gopalganj, Samastipur, Katihar, Khagaria, Bhojpur, Buxar, Darbhanga, Saharsa, Kaimur (Bhabua), Rohtas, Jamui, Banka, Nawada, Gaya, Munger, Vaishali, Begusarai, Bhagalpur, Lakhisarai, Sheikhpura, Arwal, Jehanabad, Nalanda, Patna, Saran, Siwan, Muzaffarpur, Madhepura, Araria, Supaul, Madhubani, Purnia, Kishanganj, Aurangabad, Amroha, Hapur, Bareilly, Pilibhit, Bulandshahr, Gautam Buddha Nagar, Kheri, Budaun, Bahraich, Shahjahanpur, Aligarh, Kasganj, Mathura, SShrawasti, Sitapur, Hathras, Etah, Hardoi, Farrukhabad, Firozabad, Siddharthnagar, Mainpuri, Mahrajganj, Agra, Gonda, Bara Banki, Kushinagar, Kannauj, Lucknow, Basti, Gorakhpur, Sant Kabir Nagar, Unnao, Etawah, Kanpur nagar Nagar, Auraiya, Ayodhya, Kanpur nagar Dehat, Deoria, Sultanpur, Ambedkar Nagar, Rae Bareli, Jalaun, Azamgarh, Mau, Fatehpur, Ballia, Jaunpur, Jhansi, Banda, Ghazipurr, Kaushambi, Prayagraj, Varanasi, Chitrakoot, Chandauli, Bhadohi, Mirzapur, Lalitpur, Sonbhadra, Amethi, Ghaziabad, Sambhal, Mahoba, Saharanpur, Bijnor, Muzaffarnagar, Baghpat, Meerut, Moradabad, Rampur, Shamli, Balrampur, Hamirpur, Pratapgarh', 'Surat', 'Darjeeling, Jalpaiguri, Cooch Behar', 'Gangtok,Gangtok']

[State]
dtype: str
sample values:
['Assam', 'Maharashtra, Gujarat', 'Uttar Pradesh', 'Odisha, Bihar, Uttar Pradesh, Madhya Pradesh, Rajasthan, Haryana', 'Assam']

[Latitude]
dtype: float64
sample values:
[]

[Longitude]
dtype: float64
sample values:
[]

[Severity]
dtype: float64
sample values:
[]

[Area Affected]
dtype: float64
sample values:
[]

[Human fatality]
dtype: float64
sample values:
[80.0, 223.0, 100.0, 1025.0, 8.0]

[Human injured]
dtype: float64
sample values:
[2.0, 1.0, 6.0, 2.0, 23.0]

[Human Displaced]
dtype: str
sample values:
['5', '2', '2', '5', '1']

[Animal Fatality]
dtype: str
sample values:
['2000', '12', '500', '500', '42']

[Description of Casualties/injured]
dtype: str
sample values:
['More than 1,05000 people were reported to be rendered destitude', 'Flooded vast areas in West Bengal resulting in the death of some 80 persons', 'Death toll reported was 223 due to flood, landslide,house collapse', 'Death of 100 people', '1025 human lives were lost ']

[Extent of damage ]
dtype: str
sample values:
['Marooning of Barwer Express', 'Affecting about one million people,an area of over 5,00,000 hectares including cropped area of 81,000 hectares', 'Causing floods in West Bengal, Kolkata recieved 18cms of rain on 9th the heaviest fall in July in last 50 years. On the same day Krishnanagar had 26cms. Bagati 24cms,Jamshedpur 18 cms', 'One passenger train was marooned in flood waters near Makrana in Rajasthan.', 'Completely wiped out']

[Event Source]
dtype: str
sample values:
['IMD', 'IMD', 'IMD', 'IMD', 'IMD']

[Event Souce ID]
dtype: float64
sample values:
[]

[District_LGD_Codes]
dtype: str
sample values:
['348, 352, 356, None, 368, 345, 349, 350, 359, 367, 362, 358, 355, 432, 484, 370, 363, 364, 344, 360, 354, 353, 365, 373, 361, 346, 357, 347, 351, 371, 211, 213, 221, 220, 197, 217, 201, 202, 193, 194, 195, 216, None, 215, 198, 190, 210, 196, 207, 224, 191, 192, 204, 219, 611, 199, 209, 520, 218, 222, 208, 205, 188, 223, 206, 214, 203, 189, 154, 502, 130, 173, 134, 144, 159, 133, 125, 180, 119, 633, 167, None, 183, 163, 138, 150, 141, 143, 182, 166, 164, 118, 514, 129, 160, 155, 162, 131, 148, 178, 186, 139, None, 122, 140, None, 137, 185, 121, 175, 151, 123, 24, 142, 126, 152, 153, 456, None, 158, 120, 187, 136, 135, 179, 170, 161, 184, 640, 145, 659, 165, 177, 132, 172, 124, 169, 171, 649, 660, 649, 17, 629, 397, 417, 395, 407, 431, 432, 434, 419, 72, 426, 406, 391, 416, 638, 433, 300, 400, 430, 437, 422, 429, 413, 436, 423, 396, 435, 421, 427, 411, 402, 390, 412, 404, 418, 536, 410, 415, 409, 428, 639, 399, 336, None, 405, 392, 393, 667, 401, 398, 420, 394, 722, 96, 106, 103, 114, 87, 102, 107, 760, 110, 97, 108, 98, 90, 113, 116, 111, 92, 104, 94, 109, 115, 366, 117, 105, 99, 88, 86, 112, 95, 100, 101, 93, 629, 64, 62, 60, 69, 72, 604, 619, 701, 76, 68, 66, 74, 67, 65, 61, 204, 71, 75, 59, 73, 70, 58', '558, 567, 561, 562, 563, 566, 556, 555, 554, 560, 564, 559, 565, 557, 96, None, 103, 114, 87, 102, 107, 760, 110, 97, 108, 98, 90, 113, 116, 111, 92, 104, 94, 109, 115, 366, 117, 105, 99, 88, 86, 112, 95, 100, 101, 93, 629, 64, 62, 60, 69, 72, 604, 619, 701, 76, 68, 66, 74, 67, 65, 61, 204, 71, 75, 59, 73, 70, 58, 211, 213, 221, 220, 197, 217, 201, 202, 193, 194, 195, 216, None, 215, 198, 190, 210, 196, 207, 224, 191, 192, 204, 219, 611, 199, 209, 520, 218, 222, 208, 205, 188, 223, 206, 214, 203, 189, 154, 502, 130, 173, 134, 144, 159, 133, 125, 180, 119, 633, 167, None, 183, 163, 138, 150, 141, 143, 182, 166, 164, 118, 514, 129, 160, 155, 162, 131, 148, 178, 186, 139, None, 122, 140, None, 137, 185, 121, 175, 151, 123, 24, 142, 126, 152, 153, 456, None, 158, 120, 187, 136, 135, 179, 170, 161, 184, 640, 145, 659, 165, 177, 132, 172, 124, 169, 171, 649, 660, 649, 17, 629', '459', '309, 314, 308', '225, 225']

[State_Codes]
dtype: str
sample values:
['18', '27,24', '9', '21,10,9,23,8,6', '18']

In [6]:
# Exact raw column-name inspection
# IMPORTANT: This does NOT modify df_raw.

print("EXACT RAW COLUMN NAMES")
print("=" * 100)

for i, column in enumerate(df_raw.columns, start=1):
    print(f"{i:>2}. repr = {repr(column)}")
    print(f"    length = {len(column)}")

print("\n" + "=" * 100)
print("COLUMNS CONTAINING 'damage', 'casual', 'fatal', 'injur', or 'displac'")
print("=" * 100)

keywords = ["damage", "casual", "fatal", "injur", "displac"]

for column in df_raw.columns:
    if any(keyword in str(column).lower() for keyword in keywords):
        print(repr(column))

EXACT RAW COLUMN NAMES
====================================================================================================
 1. repr = 'Unnamed: 0'
    length = 10
 2. repr = 'UEI'
    length = 3
 3. repr = 'Start Date'
    length = 10
 4. repr = 'End Date'
    length = 8
 5. repr = 'Duration(Days)'
    length = 14
 6. repr = 'Main Cause'
    length = 10
 7. repr = 'Location'
    length = 8
 8. repr = 'Districts'
    length = 9
 9. repr = 'State'
    length = 5
10. repr = 'Latitude'
    length = 8
11. repr = 'Longitude'
    length = 9
12. repr = 'Severity'
    length = 8
13. repr = 'Area Affected'
    length = 13
14. repr = 'Human fatality'
    length = 14
15. repr = 'Human injured'
    length = 13
16. repr = 'Human Displaced'
    length = 15
17. repr = 'Animal Fatality'
    length = 15
18. repr = 'Description of Casualties/injured'
    length = 33
19. repr = 'Extent of damage '
    length = 17
20. repr = 'Event Source'
    length = 12
21. repr = 'Event Souce ID'
    length = 14
22. repr = 'District_LGD_Codes'
    length = 18
23. repr = 'State_Codes'
    length = 11

====================================================================================================
COLUMNS CONTAINING 'damage', 'casual', 'fatal', 'injur', or 'displac'
====================================================================================================
'Human fatality'
'Human injured'
'Human Displaced'
'Animal Fatality'
'Description of Casualties/injured'
'Extent of damage '

In [7]:
# Automatically identify potential impact/outcome columns
# based only on their actual column names.

impact_keywords = [
    "fatal",
    "injur",
    "displac",
    "damage",
    "casual",
    "affected",
    "death",
    "loss"
]

impact_candidates = [
    column
    for column in df_raw.columns
    if any(keyword in str(column).lower() for keyword in impact_keywords)
]

print("POTENTIAL IMPACT / OUTCOME COLUMNS")
print("=" * 100)

for i, column in enumerate(impact_candidates, start=1):
    series = df_raw[column]

    print(f"\n{i}. {repr(column)}")
    print(f"   dtype: {series.dtype}")
    print(f"   non-null: {series.notna().sum()}")
    print(f"   missing: {series.isna().sum()}")
    print(f"   missing %: {series.isna().mean() * 100:.2f}%")
    print(f"   unique non-null: {series.nunique(dropna=True)}")

    print("   sample values:")
    for value in series.dropna().astype(str).head(10):
        print(f"      {value}")

POTENTIAL IMPACT / OUTCOME COLUMNS
====================================================================================================

1. 'Area Affected'
   dtype: float64
   non-null: 0
   missing: 6876
   missing %: 100.00%
   unique non-null: 0
   sample values:

2. 'Human fatality'
   dtype: float64
   non-null: 3770
   missing: 3106
   missing %: 45.17%
   unique non-null: 183
   sample values:
      80.0
      223.0
      100.0
      1025.0
      8.0
      50.0
      90.0
      3.0
      90.0
      144.0

3. 'Human injured'
   dtype: float64
   non-null: 1058
   missing: 5818
   missing %: 84.61%
   unique non-null: 62
   sample values:
      2.0
      1.0
      6.0
      2.0
      23.0
      40.0
      22.0
      2.0
      20.0
      1.0

4. 'Human Displaced'
   dtype: str
   non-null: 122
   missing: 6754
   missing %: 98.23%
   unique non-null: 23
   sample values:
      5
      2
      2
      5
      1
      50
      2
      1
      3
      9

5. 'Animal Fatality'
   dtype: str
   non-null: 571
   missing: 6305
   missing %: 91.70%
   unique non-null: 247
   sample values:
      2000
      12
      500
      500
      42
      25
      500
      425
      2000
      300

6. 'Description of Casualties/injured'
   dtype: str
   non-null: 3267
   missing: 3609
   missing %: 52.49%
   unique non-null: 2487
   sample values:
      More than 1,05000 people were reported to be rendered destitude
      Flooded vast areas in West Bengal resulting in the death of some 80 persons
      Death toll reported was 223 due to flood, landslide,house collapse
      Death of 100 people
      1025 human lives were lost
      8 persons reported dead in house collapse
      50 persons reported dead
      About 90 persons were reported to have died in floods
      3 lives were lost,hundreds of wild animals washed away
      90 persons were reported washed away

7. 'Extent of damage '
   dtype: str
   non-null: 3755
   missing: 3121
   missing %: 45.39%
   unique non-null: 3612
   sample values:
      Marooning of Barwer Express
      Affecting about one million people,an area of over 5,00,000 hectares including cropped area of 81,000 hectares
      Causing floods in West Bengal, Kolkata recieved 18cms of rain on 9th the heaviest fall in July in last 50 years. On the same day Krishnanagar had 26cms. Bagati 24cms,Jamshedpur 18 cms
      One passenger train was marooned in flood waters near Makrana in Rajasthan.
      Completely wiped out
      Rail amd road communications with Mumbai were cut off for nearly a month
      Pedong recorded 60 cms on 3rd, 70cms in 4th,76 cms on 5th, Sankos recieved 76cms on 3rd, 64 cms on 4th,40 cms on 5th. The havoc caused beggars description the area affected presenting a picture of death,devastation all round
      Rendered 5 lakhs of people homeless,inundated vast areas of jute,paddy crops
      Disrupted telecommunications,road traffic in the Mandi region of Himachal Pradesh,caused floods in the Beas,Ravi inundating vast areas in Hoshiarpur. Kapurthala,Gurdaspur district of Punjab
      Affecting vast areas in Uttar Pradesh, Bihar, North Bengal, Assam,Rajasthan. The Jammu flooded many villages near Delhi

In [8]:
# Compact value-profile for every raw column
# This is inspection only. No data is modified.

profile_rows = []

for column in df_raw.columns:
    series = df_raw[column]

    non_null = series.dropna()

    sample_values = non_null.astype(str).head(3).tolist()

    profile_rows.append({
        "Column": column,
        "Dtype": str(series.dtype),
        "Non_Null": series.notna().sum(),
        "Missing": series.isna().sum(),
        "Missing_%": round(series.isna().mean() * 100, 2),
        "Unique": series.nunique(dropna=True),
        "Sample_1": sample_values[0] if len(sample_values) > 0 else None,
        "Sample_2": sample_values[1] if len(sample_values) > 1 else None,
        "Sample_3": sample_values[2] if len(sample_values) > 2 else None
    })

column_profile = pd.DataFrame(profile_rows)

display(column_profile)

,Column,Dtype,Non_Null,Missing,Missing_%,Unique,Sample_1,Sample_2,Sample_3
0,Unnamed: 0,int64,6876,0,0.00,6876,563,564,565
1,UEI,str,6876,0,0.00,6876,UEI-IMD-FL-1967-0001,UEI-IMD-FL-1967-0002,UEI-IMD-FL-1967-0003
2,Start Date,str,6856,20,0.29,3684,02-07-1967 00:00,22-07-1967 00:00,01-08-1967 00:00
3,End Date,str,6856,20,0.29,3692,08-07-1967 00:00,28-07-1967 00:00,30-08-1967 00:00
4,Duration(Days),float64,6857,19,0.28,61,7.0,7.0,30.0
5,Main Cause,str,6845,31,0.45,579,flood,flood,flood
6,Location,float64,0,6876,100.00,0,NaN,NaN,NaN
7,Districts,str,6817,59,0.86,2892,"Bhadrak, Dhenkanal, Jajapur, Subarnapur, Nuapa...","Kasaragod, Wayanad, Kozhikode, Malappuram, Pal...",Surat
8,State,str,6876,0,0.00,82,Assam,"Maharashtra, Gujarat",Uttar Pradesh
9,Latitude,float64,0,6876,100.00,0,NaN,NaN,NaN
10,Longitude,float64,0,6876,100.00,0,NaN,NaN,NaN
11,Severity,float64,0,6876,100.00,0,NaN,NaN,NaN
12,Area Affected,float64,0,6876,100.00,0,NaN,NaN,NaN
13,Human fatality,float64,3770,3106,45.17,183,80.0,223.0,100.0
14,Human injured,float64,1058,5818,84.61,62,2.0,1.0,6.0
15,Human Displaced,str,122,6754,98.23,23,5,2,2
16,Animal Fatality,str,571,6305,91.70,247,2000,12,500
17,Description of Casualties/injured,str,3267,3609,52.49,2487,"More than 1,05000 people were reported to be r...",Flooded vast areas in West Bengal resulting in...,"Death toll reported was 223 due to flood, land..."
18,Extent of damage,str,3755,3121,45.39,3612,Marooning of Barwer Express,"Affecting about one million people,an area of ...","Causing floods in West Bengal, Kolkata recieve..."
19,Event Source,str,6876,0,0.00,1,IMD,IMD,IMD
20,Event Souce ID,float64,0,6876,100.00,0,NaN,NaN,NaN
21,District_LGD_Codes,str,6572,304,4.42,2482,"348, 352, 356, None, 368, 345, 349, 350, 359, ...","558, 567, 561, 562, 563, 566, 556, 555, 554, 5...",459
22,State_Codes,str,6618,258,3.75,65,18,"27,24",9

In [9]:
# Numerical-column summary

numeric_columns = df_raw.select_dtypes(include="number").columns.tolist()

print("NUMERICAL COLUMNS")
print("=" * 100)
print(numeric_columns)

if numeric_columns:
    numerical_summary = df_raw[numeric_columns].describe().T

    numerical_summary["missing"] = df_raw[numeric_columns].isna().sum()
    numerical_summary["missing_%"] = (
        df_raw[numeric_columns].isna().mean() * 100
    ).round(2)

    display(numerical_summary)
else:
    print("No numerical columns found.")

NUMERICAL COLUMNS
====================================================================================================
['Unnamed: 0', 'Duration(Days)', 'Location', 'Latitude', 'Longitude', 'Severity', 'Area Affected', 'Human fatality', 'Human injured', 'Event Souce ID']

,count,mean,std,min,25%,50%,75%,max,missing,missing_%
Unnamed: 0,6876.0,4000.500000,1985.074558,563.0,2281.75,4000.5,5719.25,7438.0,0,0.00
Duration(Days),6857.0,3.613096,9.817698,1.0,1.00,1.0,3.00,365.0,19,0.28
Location,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6876,100.00
Latitude,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6876,100.00
Longitude,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6876,100.00
Severity,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6876,100.00
Area Affected,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6876,100.00
Human fatality,3770.0,18.751459,104.858208,1.0,1.00,3.0,10.00,5000.0,3106,45.17
Human injured,1058.0,10.998110,71.074255,1.0,2.00,3.0,7.00,2000.0,5818,84.61
Event Souce ID,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6876,100.00

In [10]:
# Categorical / string-column cardinality summary

string_columns = df_raw.select_dtypes(include=["object", "string"]).columns.tolist()

categorical_summary = []

for column in string_columns:
    series = df_raw[column]

    categorical_summary.append({
        "Column": column,
        "Unique": series.nunique(dropna=True),
        "Missing": series.isna().sum(),
        "Missing_%": round(series.isna().mean() * 100, 2),
        "Most_Frequent": series.value_counts(dropna=True).index[0]
            if series.notna().any() else None,
        "Most_Frequent_Count": series.value_counts(dropna=True).iloc[0]
            if series.notna().any() else 0
    })

categorical_summary = pd.DataFrame(categorical_summary)

display(categorical_summary)

,Column,Unique,Missing,Missing_%,Most_Frequent,Most_Frequent_Count
0,UEI,6876,0,0.00,UEI-IMD-FL-1967-0001,1
1,Start Date,3684,20,0.29,17-05-2022 00:00,41
2,End Date,3692,20,0.29,11-07-2023 00:00,31
3,Main Cause,579,31,0.45,heavy rains,2628
4,Districts,2892,59,0.86,Mumbai,88
5,State,82,0,0.00,Maharashtra,1012
6,Human Displaced,23,6754,98.23,1,45
7,Animal Fatality,247,6305,91.70,1,53
8,Description of Casualties/injured,2487,3609,52.49,One person died.,63
9,Extent of damage,3612,3121,45.39,Landslide reported.,17
10,Event Source,1,0,0.00,IMD,6876
11,District_LGD_Codes,2482,304,4.42,565,97
12,State_Codes,65,258,3.75,27,1012

In [11]:
# Investigate where High_Impact appears in the local repository.
# This is inspection only. No files are modified.

from pathlib import Path

print("SEARCHING LOCAL REPOSITORY FOR 'High_Impact'")
print("=" * 100)

search_root = PROJECT_ROOT

matches = []

for path in search_root.rglob("*"):
    if not path.is_file():
        continue

    # Skip virtual environments and Git internals
    if ".venv" in path.parts or ".git" in path.parts:
        continue

    # Only inspect relevant text/code/data files
    if path.suffix.lower() not in {
        ".py", ".ipynb", ".csv", ".txt", ".md"
    }:
        continue

    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        continue

    if "High_Impact" in text:
        matches.append(path.relative_to(PROJECT_ROOT))

if matches:
    print("Files containing 'High_Impact':")
    for path in matches:
        print(" -", path)
else:
    print("No occurrences of 'High_Impact' found.")

SEARCHING LOCAL REPOSITORY FOR 'High_Impact'
====================================================================================================
Files containing 'High_Impact':
 - notebooks\01_india_dataset_discovery.ipynb
 - notebooks\02_data_cleaning.py
 - notebooks\03_feature_engineering.py
 - notebooks\04_model_training.py
 - notebooks\05_model_evaluation.py
 - notebooks\06_robust_validation.py
 - data\processed\India_Flood_Inventory_cleaned.csv
 - data\processed\India_Flood_Inventory_features.csv

In [12]:
# Inspect existing India processed datasets.
# These files are being audited, not trusted.

CLEANED_PATH = (
    PROJECT_ROOT / "data" / "processed"
    / "India_Flood_Inventory_cleaned.csv"
)

FEATURES_PATH = (
    PROJECT_ROOT / "data" / "processed"
    / "India_Flood_Inventory_features.csv"
)

print("EXISTING INDIA PROCESSED FILES")
print("=" * 100)

for name, path in [
    ("Cleaned", CLEANED_PATH),
    ("Features", FEATURES_PATH)
]:
    print(f"\n{name} dataset")
    print("-" * 100)
    print("Path:", path)
    print("Exists:", path.exists())

    if path.exists():
        temp_df = pd.read_csv(path)

        print("Shape:", temp_df.shape)
        print("Columns:")
        for i, column in enumerate(temp_df.columns, start=1):
            print(f"  {i:>2}. {repr(column)}")

        print("\nFirst 3 rows:")
        display(temp_df.head(3))

EXISTING INDIA PROCESSED FILES
====================================================================================================

Cleaned dataset
----------------------------------------------------------------------------------------------------
Path: c:\Users\KIIT\Desktop\AI-Disaster-Intelligence-System\data\processed\India_Flood_Inventory_cleaned.csv
Exists: True
Shape: (3770, 21)
Columns:
   1. 'Unnamed: 0'
   2. 'UEI'
   3. 'Start Date'
   4. 'End Date'
   5. 'Duration(Days)'
   6. 'Main Cause'
   7. 'Districts'
   8. 'State'
   9. 'Human fatality'
  10. 'Human injured'
  11. 'Human Displaced'
  12. 'Animal Fatality'
  13. 'Description of Casualties/injured'
  14. 'Extent of damage'
  15. 'Event Source'
  16. 'District_LGD_Codes'
  17. 'State_Codes'
  18. 'Start_Year'
  19. 'Start_Month'
  20. 'Start_Day'
  21. 'High_Impact'

First 3 rows:

,Unnamed: 0,UEI,Start Date,End Date,Duration(Days),Main Cause,Districts,State,Human fatality,Human injured,...,Animal Fatality,Description of Casualties/injured,Extent of damage,Event Source,District_LGD_Codes,State_Codes,Start_Year,Start_Month,Start_Day,High_Impact
0,590,UEI-IMD-FL-1970-0007,1970-09-01,1970-09-14,14.0,heavy rains,"Darjeeling, Jalpaiguri, Cooch Behar, Malda, Ut...",West Bengal,80.0,NaN,...,NaN,Flooded vast areas in West Bengal resulting in...,Rendering several thousands homeless. There wa...,IMD,NaN,19.0,1970.0,9.0,1.0,1
1,591,UEI-IMD-FL-1970-0008,1970-09-27,1970-09-30,4.0,floods,NaN,Uttar Pradesh,223.0,NaN,...,NaN,"Death toll reported was 223 due to flood, land...","Crops,property damage have been estimated to r...",IMD,NaN,9.0,1970.0,9.0,27.0,1
2,594,UEI-IMD-FL-1970-0011,1970-09-22,1970-09-22,1.0,torrential rain,NaN,Telangana,100.0,NaN,...,NaN,Death of 100 people,Stored grains worth lakhs of rupees were washe...,IMD,NaN,36.0,1970.0,9.0,22.0,1

Features dataset
----------------------------------------------------------------------------------------------------
Path: c:\Users\KIIT\Desktop\AI-Disaster-Intelligence-System\data\processed\India_Flood_Inventory_features.csv
Exists: True
Shape: (3770, 23)
Columns:
   1. 'Duration(Days)'
   2. 'Main Cause'
   3. 'Districts'
   4. 'State'
   5. 'Extent of damage'
   6. 'Event Source'
   7. 'District_LGD_Codes'
   8. 'State_Codes'
   9. 'Start_Year'
  10. 'Start_Month'
  11. 'Start_Day'
  12. 'High_Impact'
  13. 'Year'
  14. 'Month'
  15. 'Day'
  16. 'Quarter'
  17. 'Month_Sin'
  18. 'Month_Cos'
  19. 'Long_Event'
  20. 'Cause_Group'
  21. 'State_Count'
  22. 'District_Count'
  23. 'Event_Source_Available'

First 3 rows:

,Duration(Days),Main Cause,Districts,State,Extent of damage,Event Source,District_LGD_Codes,State_Codes,Start_Year,Start_Month,...,Month,Day,Quarter,Month_Sin,Month_Cos,Long_Event,Cause_Group,State_Count,District_Count,Event_Source_Available
0,14.0,heavy rains,"Darjeeling, Jalpaiguri, Cooch Behar, Malda, Ut...",West Bengal,Rendering several thousands homeless. There wa...,IMD,NaN,19.0,1970.0,9.0,...,9.0,1.0,3.0,-1.0,-1.836970e-16,1,Heavy Rain,1,8,1
1,4.0,floods,NaN,Uttar Pradesh,"Crops,property damage have been estimated to r...",IMD,NaN,9.0,1970.0,9.0,...,9.0,27.0,3.0,-1.0,-1.836970e-16,0,Other,1,0,1
2,1.0,torrential rain,NaN,Telangana,Stored grains worth lakhs of rupees were washe...,IMD,NaN,36.0,1970.0,9.0,...,9.0,22.0,3.0,-1.0,-1.836970e-16,0,Heavy Rain,1,0,1

In [13]:
# Inspect High_Impact wherever it exists.
# We are NOT assuming that it is a valid target.

for name, path in [
    ("Cleaned", CLEANED_PATH),
    ("Features", FEATURES_PATH)
]:
    if not path.exists():
        continue

    temp_df = pd.read_csv(path)

    if "High_Impact" in temp_df.columns:
        print("\n" + "=" * 100)
        print(f"HIGH_IMPACT FOUND IN: {name}")
        print("=" * 100)

        target = temp_df["High_Impact"]

        print("dtype:", target.dtype)
        print("rows:", len(target))
        print("missing:", target.isna().sum())
        print("unique values:", target.nunique(dropna=True))

        print("\nValue counts:")
        print(target.value_counts(dropna=False).sort_index())

        print("\nSample values:")
        print(target.head(20).tolist())

    else:
        print(f"\nHigh_Impact is NOT present in {name} dataset.")

====================================================================================================
HIGH_IMPACT FOUND IN: Cleaned
====================================================================================================
dtype: int64
rows: 3770
missing: 0
unique values: 2

Value counts:
High_Impact
0    2752
1    1018
Name: count, dtype: int64

Sample values:
[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

====================================================================================================
HIGH_IMPACT FOUND IN: Features
====================================================================================================
dtype: int64
rows: 3770
missing: 0
unique values: 2

Value counts:
High_Impact
0    2752
1    1018
Name: count, dtype: int64

Sample values:
[1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [15]:
from pathlib import Path
import pandas as pd
import numpy as np

# ============================================================
# RELOAD RAW INDIA DATASET FOR TARGET LEAKAGE AUDIT
# ============================================================

PROJECT_ROOT = Path.cwd().parent

RAW_FILE = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "India_Flood_Inventory_v3 (2).csv"
)

print("Raw dataset path:")
print(RAW_FILE)

print("\nFile exists:", RAW_FILE.exists())

if not RAW_FILE.exists():
    raise FileNotFoundError(
        f"Raw India dataset not found:\n{RAW_FILE}"
    )

df = pd.read_csv(RAW_FILE)

print("\nRaw India dataset reloaded successfully.")
print("Shape:", df.shape)

print("\nColumns:")
for i, column in enumerate(df.columns, start=1):
    print(f"{i:>2}. {repr(column)}")

Raw dataset path:
c:\Users\KIIT\Desktop\AI-Disaster-Intelligence-System\data\raw\India_Flood_Inventory_v3 (2).csv

File exists: True

Raw India dataset reloaded successfully.
Shape: (6876, 23)

Columns:
 1. 'Unnamed: 0'
 2. 'UEI'
 3. 'Start Date'
 4. 'End Date'
 5. 'Duration(Days)'
 6. 'Main Cause'
 7. 'Location'
 8. 'Districts'
 9. 'State'
10. 'Latitude'
11. 'Longitude'
12. 'Severity'
13. 'Area Affected'
14. 'Human fatality'
15. 'Human injured'
16. 'Human Displaced'
17. 'Animal Fatality'
18. 'Description of Casualties/injured'
19. 'Extent of damage '
20. 'Event Source'
21. 'Event Souce ID'
22. 'District_LGD_Codes'
23. 'State_Codes'

In [16]:
# ============================================================
# TARGET LEAKAGE AUDIT — RAW INDIA DATASET
# ============================================================

print("=" * 100)
print("TARGET LEAKAGE AUDIT — RAW INDIA DATASET")
print("=" * 100)

TARGET = "Human fatality"

# Work only with the raw dataset
audit_df = df.copy()

# Convert target to numeric for analysis
audit_df[TARGET] = pd.to_numeric(
    audit_df[TARGET],
    errors="coerce"
)

# Create the target exactly as the current pipeline does
audit_df["High_Impact"] = (
    audit_df[TARGET] >= 10
).astype("Int64")

print("\nTarget definition:")
print("High_Impact = 1  -> Human fatality >= 10")
print("High_Impact = 0  -> Human fatality < 10")

print("\nRows with known target:")
print(audit_df[TARGET].notna().sum())

print("\nTarget distribution among rows with known fatality:")

print(
    audit_df.loc[
        audit_df[TARGET].notna(),
        "High_Impact"
    ].value_counts(dropna=False).sort_index()
)

print("\n" + "=" * 100)
print("POTENTIAL OUTCOME / LEAKAGE COLUMNS")
print("=" * 100)

potential_columns = [
    "Human fatality",
    "Human injured",
    "Human Displaced",
    "Animal Fatality",
    "Description of Casualties/injured",
    "Extent of damage",
    "Duration(Days)",
    "Area Affected"
]

for column in potential_columns:

    if column not in audit_df.columns:
        print(f"\n{column}: NOT FOUND")
        continue

    print("\n" + "-" * 80)
    print(f"COLUMN: {repr(column)}")

    print("dtype:", audit_df[column].dtype)
    print("non-null:", audit_df[column].notna().sum())
    print("missing:", audit_df[column].isna().sum())
    print(
        "missing %:",
        round(audit_df[column].isna().mean() * 100, 2)
    )
    print("unique non-null:", audit_df[column].nunique(dropna=True))

    print("\nSample non-null values:")

    values = (
        audit_df[column]
        .dropna()
        .head(10)
        .tolist()
    )

    for value in values:
        print(" ", repr(value))

====================================================================================================
TARGET LEAKAGE AUDIT — RAW INDIA DATASET
====================================================================================================

Target definition:
High_Impact = 1  -> Human fatality >= 10
High_Impact = 0  -> Human fatality < 10

Rows with known target:
3770

Target distribution among rows with known fatality:
High_Impact
0    2752
1    1018
Name: count, dtype: Int64

====================================================================================================
POTENTIAL OUTCOME / LEAKAGE COLUMNS
====================================================================================================

--------------------------------------------------------------------------------
COLUMN: 'Human fatality'
dtype: float64
non-null: 3770
missing: 3106
missing %: 45.17
unique non-null: 183

Sample non-null values:
  80.0
  223.0
  100.0
  1025.0
  8.0
  50.0
  90.0
  3.0
  90.0
  144.0

--------------------------------------------------------------------------------
COLUMN: 'Human injured'
dtype: float64
non-null: 1058
missing: 5818
missing %: 84.61
unique non-null: 62

Sample non-null values:
  2.0
  1.0
  6.0
  2.0
  23.0
  40.0
  22.0
  2.0
  20.0
  1.0

--------------------------------------------------------------------------------
COLUMN: 'Human Displaced'
dtype: str
non-null: 122
missing: 6754
missing %: 98.23
unique non-null: 23

Sample non-null values:
  '5'
  '2'
  '2'
  '5'
  '1'
  '50'
  '2'
  '1'
  '3'
  '9'

--------------------------------------------------------------------------------
COLUMN: 'Animal Fatality'
dtype: str
non-null: 571
missing: 6305
missing %: 91.7
unique non-null: 247

Sample non-null values:
  '2000'
  '12'
  '500'
  '500'
  '42'
  '25'
  '500'
  '425'
  '2000'
  '300'

--------------------------------------------------------------------------------
COLUMN: 'Description of Casualties/injured'
dtype: str
non-null: 3267
missing: 3609
missing %: 52.49
unique non-null: 2487

Sample non-null values:
  'More than 1,05000 people were reported to be rendered destitude'
  'Flooded vast areas in West Bengal resulting in the death of some 80 persons'
  'Death toll reported was 223 due to flood, landslide,house collapse'
  'Death of 100 people'
  '1025 human lives were lost '
  '8 persons reported dead in house collapse'
  '50 persons reported dead'
  'About 90 persons were reported to have died in floods'
  '3 lives were lost,hundreds of wild animals washed away'
  '90 persons were reported washed away'

Extent of damage: NOT FOUND

--------------------------------------------------------------------------------
COLUMN: 'Duration(Days)'
dtype: float64
non-null: 6857
missing: 19
missing %: 0.28
unique non-null: 61

Sample non-null values:
  7.0
  7.0
  30.0
  2.0
  7.0
  5.0
  30.0
  1.0
  8.0
  8.0

--------------------------------------------------------------------------------
COLUMN: 'Area Affected'
dtype: float64
non-null: 0
missing: 6876
missing %: 100.0
unique non-null: 0

Sample non-null values:

In [17]:
# ============================================================
# COMPACT LEAKAGE AUDIT SUMMARY
# ============================================================

audit_columns = [
    "Human fatality",
    "Human injured",
    "Human Displaced",
    "Animal Fatality",
    "Description of Casualties/injured",
    "Extent of damage",
    "Duration(Days)",
    "Area Affected"
]

rows = []

for column in audit_columns:

    if column not in df.columns:
        continue

    series = df[column]

    rows.append({
        "Column": repr(column),
        "Dtype": str(series.dtype),
        "Non_Null": int(series.notna().sum()),
        "Missing": int(series.isna().sum()),
        "Missing_%": round(series.isna().mean() * 100, 2),
        "Unique": int(series.nunique(dropna=True)),
        "Example_1": str(series.dropna().iloc[0])
        if series.notna().any() else "",
        "Example_2": str(series.dropna().iloc[1])
        if series.notna().sum() > 1 else "",
        "Example_3": str(series.dropna().iloc[2])
        if series.notna().sum() > 2 else ""
    })

leakage_summary = pd.DataFrame(rows)

display(leakage_summary)

,Column,Dtype,Non_Null,Missing,Missing_%,Unique,Example_1,Example_2,Example_3
0,'Human fatality',float64,3770,3106,45.17,183,80.0,223.0,100.0
1,'Human injured',float64,1058,5818,84.61,62,2.0,1.0,6.0
2,'Human Displaced',str,122,6754,98.23,23,5,2,2
3,'Animal Fatality',str,571,6305,91.70,247,2000,12,500
4,'Description of Casualties/injured',str,3267,3609,52.49,2487,"More than 1,05000 people were reported to be r...",Flooded vast areas in West Bengal resulting in...,"Death toll reported was 223 due to flood, land..."
5,'Duration(Days)',float64,6857,19,0.28,61,7.0,7.0,30.0
6,'Area Affected',float64,0,6876,100.00,0,,,

In [22]:
# ============================================================
# CASUALTY DESCRIPTION — TARGET LEAKAGE INVESTIGATION
# ============================================================

print("=" * 100)
print("CASUALTY DESCRIPTION — TARGET LEAKAGE INVESTIGATION")
print("=" * 100)

TEXT_COLUMN = "Description of Casualties/injured"
TARGET_COLUMN = "Human fatality"

if TEXT_COLUMN not in audit_df.columns:
    raise ValueError(f"Column '{TEXT_COLUMN}' not found.")

# Work from audit_df because it already contains High_Impact
analysis_df = audit_df.copy()

analysis_df[TEXT_COLUMN] = (
    analysis_df[TEXT_COLUMN]
    .astype("string")
    .str.lower()
    .str.strip()
)

print(
    "\nRows with known Human fatality:",
    len(analysis_df)
)

# ------------------------------------------------------------
# FATALITY-RELATED TERMS
# ------------------------------------------------------------

terms = [
    "death",
    "deaths",
    "died",
    "dead",
    "fatality",
    "fatalities",
    "killed",
    "casualties",
    "life lost",
    "lives lost",
    "washed away"
]

results = []

for term in terms:

    mask = (
        analysis_df[TEXT_COLUMN]
        .fillna("")
        .str.contains(term, regex=False)
    )

    results.append({
        "Term": term,
        "Rows_Containing_Term": int(mask.sum()),
        "High_Impact_Rows": int(
            analysis_df.loc[mask, "High_Impact"].sum()
        ),
        "Low_Impact_Rows": int(
            mask.sum()
            - analysis_df.loc[mask, "High_Impact"].sum()
        )
    })

results_df = pd.DataFrame(results)

print("\nFatality-related terminology frequency:")
print("-" * 100)

display(results_df)

# ------------------------------------------------------------
# REPRESENTATIVE MATCHING DESCRIPTIONS
# ------------------------------------------------------------

combined_mask = (
    analysis_df[TEXT_COLUMN]
    .fillna("")
    .apply(
        lambda text: any(
            term in text
            for term in terms
        )
    )
)

matching = analysis_df.loc[
    combined_mask
].copy()

print("\n")
print("=" * 100)
print("REPRESENTATIVE DESCRIPTIONS CONTAINING FATALITY TERMS")
print("=" * 100)

print(
    "\nNumber of matching rows:",
    len(matching)
)

if len(matching) > 0:

    display(
        matching[
            [
                TARGET_COLUMN,
                "High_Impact",
                TEXT_COLUMN
            ]
        ]
        .head(20)
    )

====================================================================================================
CASUALTY DESCRIPTION — TARGET LEAKAGE INVESTIGATION
====================================================================================================

Rows with known Human fatality: 3770

Fatality-related terminology frequency:
----------------------------------------------------------------------------------------------------

           Term  Rows_Containing_Term  High_Impact_Rows  Low_Impact_Rows
0         death                    18                15                3
1        deaths                     6                 5                1
2          died                  2426               862             1564
3          dead                    11                 8                3
4      fatality                     0                 0                0
5    fatalities                     0                 0                0
6        killed                    86                30               56
7    casualties                     0                 0                0
8     life lost                     2                 0                2
9    lives lost                    18                16                2
10  washed away                   195                48              147

====================================================================================================
REPRESENTATIVE DESCRIPTIONS CONTAINING FATALITY TERMS
====================================================================================================

Number of matching rows: 2637

,Human fatality,High_Impact,Description of Casualties/injured
0,80.0,1,flooded vast areas in west bengal resulting in...
1,223.0,1,"death toll reported was 223 due to flood, land..."
2,100.0,1,death of 100 people
4,8.0,0,8 persons reported dead in house collapse
5,50.0,1,50 persons reported dead
6,90.0,1,about 90 persons were reported to have died in...
7,3.0,0,"3 lives were lost,hundreds of wild animals was..."
8,90.0,1,90 persons were reported washed away
9,144.0,1,atleast 144 persons died
11,13.0,1,13 people washed away
12,79.0,1,death of 79 persons
13,66.0,1,66 deaths occured.
14,145.0,1,about 145 lives lost
17,17.0,1,"burying 10 people, killed 7 people,about a doz..."
21,43.0,1,as many as 43 people died due to house collapses
25,44.0,1,"500 heads of cattle were lost ,the death toll ..."
28,228.0,1,death toll in the current up floods mounted to...
30,68.0,1,the death toll rose to 68
33,15.0,1,15 heads of cattle aand 2000 sheep were washed...
35,2.0,0,2 children were washed away in wild streams

In [24]:
# ============================================================
# EXTENT OF DAMAGE — TARGET LEAKAGE INVESTIGATION
# ============================================================

print("=" * 100)
print("EXTENT OF DAMAGE — TARGET LEAKAGE INVESTIGATION")
print("=" * 100)

TEXT_COLUMN = "Extent of damage "
TARGET_COLUMN = "Human fatality"

if TEXT_COLUMN not in audit_df.columns:
    raise ValueError(f"Column '{TEXT_COLUMN}' not found.")

analysis_df = audit_df.copy()

analysis_df[TEXT_COLUMN] = (
    analysis_df[TEXT_COLUMN]
    .astype("string")
    .str.lower()
    .str.strip()
)

print(
    "\nRows with known Human fatality:",
    len(analysis_df)
)

# ------------------------------------------------------------
# FATALITY-RELATED TERMS
# ------------------------------------------------------------

terms = [
    "death",
    "deaths",
    "died",
    "dead",
    "fatality",
    "fatalities",
    "killed",
    "casualties",
    "life lost",
    "lives lost",
    "people lost",
    "persons lost",
    "people died",
    "persons died",
    "people killed",
    "persons killed",
    "washed away"
]

results = []

for term in terms:

    mask = (
        analysis_df[TEXT_COLUMN]
        .fillna("")
        .str.contains(term, regex=False)
    )

    total_count = int(mask.sum())

    high_count = int(
        analysis_df.loc[
            mask,
            "High_Impact"
        ].sum()
    )

    results.append({
        "Term": term,
        "Rows_Containing_Term": total_count,
        "High_Impact_Rows": high_count,
        "Low_Impact_Rows": total_count - high_count
    })

results_df = pd.DataFrame(results)

print("\nFatality-related terminology frequency:")
print("-" * 100)

display(results_df)

# ------------------------------------------------------------
# REPRESENTATIVE MATCHING DESCRIPTIONS
# ------------------------------------------------------------

combined_mask = (
    analysis_df[TEXT_COLUMN]
    .fillna("")
    .apply(
        lambda text: any(
            term in text
            for term in terms
        )
    )
)

matching = analysis_df.loc[
    combined_mask
].copy()

print("\n")
print("=" * 100)
print("REPRESENTATIVE EXTENT-OF-DAMAGE DESCRIPTIONS")
print("=" * 100)

print(
    "\nNumber of matching rows:",
    len(matching)
)

if len(matching) > 0:

    display(
        matching[
            [
                TARGET_COLUMN,
                "High_Impact",
                TEXT_COLUMN
            ]
        ]
        .head(30)
    )

====================================================================================================
EXTENT OF DAMAGE — TARGET LEAKAGE INVESTIGATION
====================================================================================================

Rows with known Human fatality: 3770

Fatality-related terminology frequency:
----------------------------------------------------------------------------------------------------

              Term  Rows_Containing_Term  High_Impact_Rows  Low_Impact_Rows
0            death                     3                 2                1
1           deaths                     0                 0                0
2             died                     0                 0                0
3             dead                     1                 0                1
4         fatality                     0                 0                0
5       fatalities                     0                 0                0
6           killed                     0                 0                0
7       casualties                     0                 0                0
8        life lost                     0                 0                0
9       lives lost                     0                 0                0
10     people lost                     1                 1                0
11    persons lost                     0                 0                0
12     people died                     0                 0                0
13    persons died                     0                 0                0
14   people killed                     0                 0                0
15  persons killed                     0                 0                0
16     washed away                   224               113              111

====================================================================================================
REPRESENTATIVE EXTENT-OF-DAMAGE DESCRIPTIONS
====================================================================================================

Number of matching rows: 227

,Human fatality,High_Impact,Extent of damage
23,10.0,1,"followed by flash-floods, 150 huts were washed..."
28,228.0,1,"the flood waters of gomti had entered jaunpur,..."
31,15.0,1,"caused extensive damage to property,snapping r..."
32,3.0,0,"mumbai was lashed by torrential rains, the flo..."
43,177.0,1,"due to incessant rains,consequent flooding sev..."
54,44.0,1,"a sawmill, watermill washed away"
70,200.0,1,many houses damaged building washed away (barr...
75,29.0,1,14 bridges costing rs. 1.16 crores washed away...
79,5.0,0,"i)road,telecommunication disrupted due to heav..."
82,8.0,0,"a tourist bus washed away,passengers escaped w..."
85,4.0,0,"a bridge,an approach road washed away"
86,3.0,0,"i)30 houses washed away,1000 families affected..."
92,7.0,0,i)four trucks washe daway ii)one bridge washed...
104,9.0,0,i)mining operations in lignite mines at neywel...
107,9.0,0,i)over hundred huts washed away in flooded ama...
108,30.0,1,"i)bridge costing rs. 23 lakh, under constructi..."
111,85.0,1,i)187 villages marooned ii)about 1.5 lakh peop...
116,27.0,1,i)a large number of small dmas breached. ii)as...
117,3.0,0,"i)200 villages affected ii)crops in 80,000 hec..."
121,4.0,0,"the mebar power house,two saw-mills washed away"
126,3.0,0,"i)severe damage to paddy crops,buildings ii)lo..."
127,8.0,0,i)severe damage to paddy crops in several hect...
128,2.0,0,i)severe sea erosion in coastal areas ii)many ...
133,2.0,0,i)low lying areas flooded ii)vehicular traffic...
135,45.0,1,"i)the tiny streams of dahisar,paoisor inundate..."
137,15.0,1,i)many houses collapsed ii)300 families render...
139,220.0,1,i)h.t. towers washed away disrupting power sup...
140,21.0,1,i)125 villages marooned ii)several thousand pe...
142,1.0,0,150 huts along the bank of river washed away
146,49.0,1,i)many houses washed away ii)electrical lines ...

In [25]:
# ============================================================
# FINAL OUTCOME / LEAKAGE COLUMN AUDIT
# ============================================================

print("=" * 100)
print("FINAL OUTCOME / LEAKAGE COLUMN AUDIT")
print("=" * 100)

OUTCOME_COLUMNS = [
    "Human fatality",
    "Human injured",
    "Human Displaced",
    "Animal Fatality",
    "Description of Casualties/injured",
    "Extent of damage",
    "Area Affected"
]

print("\nColumns identified as outcome/post-event information:")
print("-" * 100)

for column in OUTCOME_COLUMNS:

    if column in audit_df.columns:

        print(
            f"EXCLUDE: {column}"
        )

    else:

        print(
            f"NOT FOUND: {column}"
        )

print("\n" + "=" * 100)
print("PROPOSED MODEL FEATURE COLUMNS")
print("=" * 100)

candidate_columns = [
    "Start Date",
    "End Date",
    "Duration(Days)",
    "Main Cause",
    "Districts",
    "State",
    "District_LGD_Codes",
    "State_Codes",
    "Event Source"
]

for column in candidate_columns:

    if column in audit_df.columns:

        print(f"KEEP CANDIDATE: {column}")

    else:

        print(f"NOT AVAILABLE: {column}")

====================================================================================================
FINAL OUTCOME / LEAKAGE COLUMN AUDIT
====================================================================================================

Columns identified as outcome/post-event information:
----------------------------------------------------------------------------------------------------
EXCLUDE: Human fatality
EXCLUDE: Human injured
EXCLUDE: Human Displaced
EXCLUDE: Animal Fatality
EXCLUDE: Description of Casualties/injured
NOT FOUND: Extent of damage
EXCLUDE: Area Affected

====================================================================================================
PROPOSED MODEL FEATURE COLUMNS
====================================================================================================
KEEP CANDIDATE: Start Date
KEEP CANDIDATE: End Date
KEEP CANDIDATE: Duration(Days)
KEEP CANDIDATE: Main Cause
KEEP CANDIDATE: Districts
KEEP CANDIDATE: State
KEEP CANDIDATE: District_LGD_Codes
KEEP CANDIDATE: State_Codes
KEEP CANDIDATE: Event Source

In [19]:
# ============================================================
# CREATE TEMPORARY TARGET FOR RAW DATA AUDIT
# ============================================================

audit_df = df.copy()

TARGET_COLUMN = "Human fatality"

audit_df[TARGET_COLUMN] = pd.to_numeric(
    audit_df[TARGET_COLUMN],
    errors="coerce"
)

audit_df = audit_df.dropna(
    subset=[TARGET_COLUMN]
).reset_index(drop=True)

audit_df["High_Impact"] = (
    audit_df[TARGET_COLUMN] >= 10
).astype(int)

print("Rows with known Human fatality:", len(audit_df))

print("\nTarget distribution:")
print(
    audit_df["High_Impact"]
    .value_counts()
    .sort_index()
)

Rows with known Human fatality: 3770

Target distribution:
High_Impact
0    2752
1    1018
Name: count, dtype: int64